### ISSUE TITLE
Unit test bundle 1 for older issues

### ISSUE THREAD

**Issue by hinshun** [openllb/hlb#91]
Tests should go in `codegen/codegen_test.go`. The input program should be as minimal as possible.

- [ ] #76 copy missing builtins for "allowWildcards", "allowEmptyWildcard", "chown", "createdTime"
- [ ] #71 unable to reuse mount within fs block
- [ ] #67 unable to pass anonymous option as argument
