### ISSUE TITLE
Unit test bundle 2 for older issues

### ISSUE THREAD

**Issue by hinshun** [openllb/hlb#92]
Tests should go in `codegen/codegen_test.go`. The input program should be as minimal as possible.

- [ ] #59 run has new builtin "ignoreCache"
- [ ] #52 stack overflow when using alias within same fs
- [ ] #40 panic from named option::run
